#!/bin/bash

# Step 1: Read the generated public key into a variable
echo -e "\n\n--------------------------------------------------------------"
echo "Step 1: Read the generated public key into a variable to lunch the agent later on ..."
echo "--------------------------------------------------------------"
JENKINS_AGENT_SSH_PUBKEY=$(cat ~/.ssh/jenkins_agent_key.pub)
echo $JENKINS_AGENT_SSH_PUBKEY

# Step 2: Create Jenkins agent
echo -e "\n\n--------------------------------------------------------------"
echo "Step 2: Creating Jenkins agent..."
echo "--------------------------------------------------------------"
sudo docker run -d --restart unless-stopped --name=jenkins-agent -p 22:22 \
--volume jenkins-volume:/var/jenkins_home \
--network jenkins-network \
-e "JENKINS_AGENT_SSH_PUBKEY=$JENKINS_AGENT_SSH_PUBKEY" \
jenkins/ssh-agent:alpine-jdk17

# Step 3: Create Jenkins agent
echo -e "\n\n--------------------------------------------------------------"
echo "Step 3: Fetching the IP address of the Jenkins agent..."
echo "--------------------------------------------------------------"
sleep 1
jenkins_agent_ip=$(sudo docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' jenkins-agent)
echo "Jenkins Agent IP address is $jenkins_agent_ip."

# Step 4: Create known_hosts file within Jenkins Master container
sleep 3
echo -e "\n\n--------------------------------------------------------------"
echo "Step 4: Creating known_hosts file within Jenkins Master container..."
echo "--------------------------------------------------------------"

sudo docker exec jenkins-master sh -c "mkdir /var/jenkins_home/.ssh"
sudo docker exec jenkins-master sh -c "touch /var/jenkins_home/.ssh/known_hosts"


# Step 5: Update known_hosts file within Jenkins Master container
sleep 3
echo -e "\n\n--------------------------------------------------------------"
echo "Step 5: Updating known_hosts within Jenkins Master container..."
echo "--------------------------------------------------------------"
sudo docker exec jenkins-master sh -c "ssh-keyscan -H $jenkins_agent_ip | tee -a /var/jenkins_home/.ssh/known_hosts"
